project_id = "juwzhovmbaokhdfjzsrq"

[functions.create-user]
verify_jwt = true

[functions.bootstrap-admin]
verify_jwt = false

[functions.notify-evaluation]
verify_jwt = false

[functions.manage-user]
verify_jwt = false

[functions.reset-all-passwords]
verify_jwt = false

[functions.clear-password-flag]
verify_jwt = false
